### ISSUE TITLE
Preparation for JOSS

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/xrnet#15]
Hey @gmweaver, here are the two projects we currently have on JOSS

openjournals/joss-reviews#1427
openjournals/joss-reviews#1493

The first thing you'll need to have is a paper like this: https://github.com/USCbiostats/fmcmc/blob/master/paper/paper.md

Here you have more info about the whole process https://joss.readthedocs.io/en/latest/submitting.html

From our meeting on the 5th

- [x] Add a table comparing xrnet with glmnet and biglasso.

- [x] Replace `penalty` with `penalty_main` and `penalty_external`.

- [ ] Treat NAs as errors in `xrnet` and `predict` methods.

**Comment by gmweaver** [comment]
Leaving check for NAs for later release (enhancement)
